export const GET_LIST_ARTICLE_SUCCESS = "GET_LIST_ARTICLE_SUCCESS";
export const GET_LIST_ARTICLE_FAILED = "GET_LIST_ARTICLE_FAILED";

export const GET_LIST_VIEW_ARTICLE_SUCCESS = "GET_LIST_VIEW_ARTICLE_SUCCESS";
export const GET_LIST_VIEW_ARTICLE_FAILED = "GET_LIST_VIEW_ARTICLE_FAILED";

export const GET_DETAIL_ARTICLE_BY_ID_SUCCESS =
  "GET_DETAIL_ARTICLE_BY_ID_SUCCESS";
export const GET_DETAIL_ARTICLE_BY_ID_FAILED =
  "GET_DETAIL_ARTICLE_BY_ID_FAILED";

export const GET_ANOTHER_ARTICLE_SUCCESS = "GET_ANOTHER_ARTICLE_SUCCESS";
export const GET_ANOTHER_ARTICLE_FAILED = "GET_ANOTHER_ARTICLE_FAILED";

export const SEARCH_ARTICLE_SUCCESS = "SEARCH_ARTICLE_SUCCESS";
export const SEARCH_ARTICLE_FAILED = "SEARCH_ARTICLE_FAILED";

export const SEARCH_ARTICLE_ADMIN_SUCCESS = "SEARCH_ARTICLE_ADMIN_SUCCESS";
export const SEARCH_ARTICLE_ADMIN_FAILED = "SEARCH_ARTICLE_ADMIN_FAILED";

export const GET_LIST_FOLLOWED_SUCCESS = "GET_LIST_FOLLOWED_SUCCESS";
export const GET_LIST_FOLLOWED_FAILED = "GET_LIST_FOLLOWED_FAILED";

export const GET_LIST_LINK_ARTICLE_SUCCESS = "GET_LIST_LINK_ARTICLE_SUCCESS";
export const GET_LIST_LINK_ARTICLE_FAILED = "GET_LIST_LINK_ARTICLE_FAILED";
