export const GET_DETAIL_COMPANY_SUCCESS = "GET_DETAIL_COMPANY_SUCCESS";
export const GET_DETAIL_COMPANY_FAILED = "GET_DETAIL_COMPANY_FAILED";
export const GET_DETAIL_COMPANY_VIEW_SUCCESS =
  "GET_DETAIL_COMPANY_VIEW_SUCCESS";
export const GET_DETAIL_COMPANY_VIEW_FAILED = "GET_DETAIL_COMPANY_VIEW_FAILED";
