export const GET_LIST_INTRODUCE_SUCCESS = "GET_LIST_INTRODUCE_SUCCESS";
export const GET_LIST_INTRODUCE_FAILED = "GET_LIST_INTRODUCE_FAILED";

export const GET_LIST_INTRODUCE_BY_ROUND_SUCCESS = "GET_LIST_INTRODUCE_BY_ROUND_SUCCESS";
export const GET_LIST_INTRODUCE_BY_ROUND_FAILED = "GET_LIST_INTRODUCE_BY_ROUND_FAILED";

export const GET_LIST_DOCUMENT_BY_ROUND_SUCCESS = "GET_LIST_DOCUMENT_BY_ROUND_SUCCESS";
export const GET_LIST_DOCUMENT_BY_ROUND_FAILED = "GET_LIST_DOCUMENT_BY_ROUND_FAILED";

export const UPDATE_INTRODUCE_SUCCESS = "UPDATE_INTRODUCE_SUCCESS";
export const UPDATE_INTRODUCE_FAILED = "UPDATE_INTRODUCE_FAILED";

export const CREATE_INTRODUCE_SUCCESS = "CREATE_INTRODUCE_SUCCESS";
export const CREATE_INTRODUCE_FAILED = "CREATE_INTRODUCE_FAILED";