export const GET_LIST_INVESTOR_FILTER_SUCCESS =
  "GET_LIST_INVESTOR_FILTER_SUCCESS";
export const GET_LIST_INVESTOR_FILTER_FAILED =
  "GET_LIST_INVESTOR_FILTER_FAILED";
export const GET_LIST_INVESTOR_SUGGEST_SUCCESS =
  "GET_LIST_INVESTOR_SUGGEST_SUCCESS";
export const GET_LIST_INVESTOR_SUGGEST_FAILED =
  "GET_LIST_INVESTOR_SUGGEST_FAILED";
