export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const START_LOADING_COMPONENT = "START_LOADING_COMPONENT";
export const STOP_LOADING_COMPONENT = "STOP_LOADING_COMPONENT";
