export const GET_LIST_ROUND_ACTIVE_BY_ID_ORGANIZATION_SUCCESS =
  "GET_LIST_ROUND_ACTIVE_BY_ID_ORGANIZATION_SUCCESS";
export const GET_LIST_ROUND_ACTIVE_BY_ID_ORGANIZATION_FAILED =
  "GET_LIST_ROUND_ACTIVE_BY_ID_ORGANIZATION_FAILED";
export const GET_LIST_ROUND_PASS_BY_ID_ORGANIZATION_SUCCESS =
  "GET_LIST_ROUND_PASS_BY_ID_ORGANIZATION_SUCCESS";
export const GET_LIST_ROUND_PASS_BY_ID_ORGANIZATION_FAILED =
  "GET_LIST_ROUND_PASS_BY_ID_ORGANIZATION_FAILED";
export const GET_LIST_ROUND_PENDING_BY_ID_ORGANIZATION_SUCCESS =
  "GET_LIST_ROUND_PENDING_BY_ID_ORGANIZATION_SUCCESS";
export const GET_LIST_ROUND_PENDING_BY_ID_ORGANIZATION_FAILED =
  "GET_LIST_ROUND_PENDING_BY_ID_ORGANIZATION_FAILED";
export const GET_ALL_LIST_ROUND_ACTIVE_SUCCESS =
  "GET_ALL_LIST_ROUND_ACTIVE_SUCCESS";
export const GET_ALL_LIST_ROUND_ACCTIVE_FAILED =
  "GET_ALL_LIST_ROUND_ACCTIVE_FAILED";
// v2
export const GET_LIST_ROUND_BY_ID_INVESTOR_SUCCESS =
  "GET_LIST_ROUND_BY_ID_INVESTOR_SUCCESS";
export const GET_LIST_ROUND_BY_ID_INVESTOR_FAILED =
  "GET_LIST_ROUND_BY_ID_INVESTOR_FAILED";
export const GET_LIST_ROUND_BY_ID_ORGANIZATION_SUCCESS =
  "GET_LIST_ROUND_BY_ID_ORGANIZATION_SUCCESS";
export const GET_LIST_ROUND_BY_ID_ORGANIZATION_FAILED =
  "GET_LIST_ROUND_BY_ID_ORGANIZATION_FAILED";

export const GET_LIST_QUESTION_AND_ANSWER_SUCCESS =
  "GET_LIST_QUESTION_AND_ANSWER_SUCCESS";
export const GET_LIST_QUESTION_AND_ANSWER_FAIL =
  "GET_LIST_QUESTION_AND_ANSWER_FAIL";

export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_FAIL = "CREATE_QUESTION_FAIL";

export const CREATE_ANSWER_SUCCESS = "CREATE_ANSWER_SUCCESS";
export const CREATE_ANSWER_FAIL = "CREATE_ANSWER_FAIL";

export const GET_ROUND_AND_ORGANIZATION_SUCCESS =
  "GET_ROUND_AND_ORGANIZATION_SUCCESS";
export const GET_ROUND_AND_ORGANIZATION_FAIL =
  "GET_ROUND_AND_ORGANIZATION_FAIL";

export const GET_LIST_DEAL_BY_ROUND_SUCCESS = "GET_LIST_DEAL_BY_ROUND_SUCCESS";
export const GET_LIST_DEAL_BY_ROUND_FAIL = "GET_LIST_DEAL_BY_ROUND_FAIL";

export const GET_LIST_ALL_ROUND_SUCCESS = "GET_LIST_ALL_ROUND_SUCCESS";
export const GET_LIST_ALL_ROUND_FAILED = "GET_LIST_ALL_ROUND_FAILED";

export const UPDATE_ROUND_SUCCESS = "UPDATE_ROUND_SUCCESS";
export const UPDATE_ROUND_FAILED = "UPDATE_ROUND_FAILED";

export const UPDATE_DOCUMENT_SUCCESS = "UPDATE_DOCUMENT_SUCCESS";
export const UPDATE_DOCUMENT_FAILED = "UPDATE_DOCUMENT_FAILED";

export const DELETE_DOCUMENT_SUCCESS = "DELETE_DOCUMENT_SUCCESS";
export const DELETE_DOCUMENT_FAILED = "DELETE_DOCUMENT_FAILED";

export const UPDATE_ROUND_STATUS_SUCCESS = "UPDATE_ROUND_STATUS_SUCCESS";
export const UPDATE_ROUND_STATUS_FAILED = "UPDATE_ROUND_STATUS_FAILED";

export const GET_ROUND_SUGGEST_SUCCESS = "GET_ROUND_SUGGEST_SUCCESS";
export const GET_ROUND_SUGGEST_FAILED = "GET_ROUND_SUGGEST_FAILED";

//
export const GET_ROUND_ACTIVE_SUCCESS_V2 = "GET_ROUND_ACTIVE_SUCCESS_V2";
export const GET_ROUND_ACTIVE_FAILED_V2 = "GET_ROUND_ACTIVE_FAILED_V2";

export const GET_ALL_ROUND_ACTIVE_SUCCESS_V2 =
  "GET_ALL_ROUND_ACTIVE_SUCCESS_V2";
export const GET_ALL_ROUND_ACTIVE_FAILED_V2 = "GET_ALL_ROUND_ACTIVE_FAILED_V2";
