export const CHECK_LOGIN_SUCCESS = "CHECK_LOGIN_SUCCESS";
export const CHECK_LOGIN_FAILED = "CHECK_LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const GET_LIST_ACCOUNT_NOT_CONFIRM_SUCCESS =
  "GET_LIST_ACCOUNT_NOT_CONFIRM_SUCCESS";
export const GET_LIST_ACCOUNT_NOT_CONFIRM_FAILED =
  "GET_LIST_ACCOUNT_NOT_CONFIRM_FAILED";
export const USER_GET_STAGE_SUCCESS = "USER_GET_STAGE_SUCCESS";
export const USER_GET_STAGE_FAILED = "USER_GET_STAGE_FAILED";
