export const GET_VALUE_LIST_INDUSTRY_SUCCESS =
  "GET_VALUE_LIST_INDUSTRY_SUCCESS";
export const GET_VALUE_LIST_INDUSTRY_FAILED = "GET_VALUE_LIST_INDUSTRY_FAILED";

export const GET_VALUE_LIST_STAGE_SUCCESS = "GET_VALUE_LIST_STAGE_SUCCESS";
export const GET_VALUE_LIST_STAGE_FAILED = "GET_VALUE_LIST_STAGE_FAILED";

export const GET_VALUE_LIST_PROVINCE_SUCCESS =
  "GET_VALUE_LIST_PROVINCE_SUCCESS";
export const GET_VALUE_LIST_PROVINCE_FAILED = "GET_VALUE_LIST_PROVINCE_FAILED";

export const GET_VALUE_LIST_REGION_SUCCESS = "GET_VALUE_LIST_REGION_SUCCESS";
export const GET_VALUE_LIST_REGION_FAILED = "GET_VALUE_LIST_REGION_FAILED";

export const GET_VALUE_ARTICLE_SUCCESS = "GET_VALUE_ARTICLE_SUCCESS";
export const GET_VALUE_ARTICLE_FAILED = "GET_VALUE_ARTICLE_FAILED";

export const GET_VALUE_ACCOUNT_SUCCESS = "GET_VALUE_ACCOUNT_SUCCESS";
export const GET_VALUE_ACCOUNT_FAILED = "GET_VALUE_ACCOUNT_FAILED";
